name: rabbitmq-server-snap
base: core18
version: '3.8.35'
summary: AMQP server written in Erlang
description: |
  RabbitMQ is an implementation of AMQP, the emerging standard for
  high performance enterprise messaging. The RabbitMQ server is a
  robust and scalable implementation of an AMQP broker.
source-code: https://github.com/nicolasbock/rabbitmq-server-snap
website: https://github.com/nicolasbock/rabbitmq-server-snap
issues: https://github.com/nicolasbock/rabbitmq-server-snap/issues
contact: https://github.com/nicolasbock/rabbitmq-server-snap/issues
icon: assets/logo.png
license: Apache-2.0
architectures:
  - build-on: [amd64]
    run-on: [amd64]
  - build-on: [i386]
    run-on: [i386]
  - build-on: [arm64]
    run-on: [arm64]
  - build-on: [armhf]
    run-on: [armhf]
  - build-on: [ppc64el]
    run-on: [ppc64el]
  - build-on: [s390x]
    run-on: [s390x]
grade: stable
confinement: strict

plugs:
  log-observe:
  mount-observe:
  network-bind:

apps:
  rabbitmq-server:
    daemon: notify
    restart-condition: on-failure
    restart-delay: 10s
    command: usr/lib/erlang/bin/rabbitmq-server
    stop-command: usr/lib/erlang/bin/rabbitmqctl stop
  rabbitmqctl:
    command: usr/lib/erlang/bin/rabbitmqctl

parts:
  rabbitmq-support:
    plugin: dump
    source: assets
    organize:
      rabbitmq-defaults: etc/rabbitmq/rabbitmq-defaults
      rabbitmq-server.service: lib/systemd/system/rabbitmq-server.service
    stage:
      - etc/rabbitmq/rabbitmq-defaults
      - lib/systemd/system/rabbitmq-server.service

  # Building rabbitmq-server from git fails because the build script downloads other
  # repositories in `deps` and uses the `master` branch of them. This leads to build
  # failures because the Erlang version is not recent enough.
  #
  # RabbitMQ dependencies: https://www.rabbitmq.com/which-erlang.html
  rabbitmq-server:
    after:
      - elixir
      - erlang
    plugin: dump
    # source: https://github.com/rabbitmq/rabbitmq-server.git
    # source-tag: rabbitmq_v3_6_10
    source: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.35/rabbitmq-server-3.8.35.tar.xz
    build-packages:
      - curl
      - python-all
      - python-simplejson
      - rsync
      - unzip
      - xmlto
      - xsltproc
      - zip
    stage-packages:
      - adduser
      - coreutils
      - libtinfo5
      - logrotate
      - lsb-base
      - socat
    override-build: |
      set -e -u -x

      echo "Starting to build rabbitmq-server at $(date)"
      START_TIME=$(date +%s)

      CPU_COUNT=$(lscpu --parse=CPU | grep -v "^#" | wc -l)

      export DESTDIR="$(readlink --canonicalize ${SNAPCRAFT_PART_INSTALL})"
      export PREFIX=/usr
      export PYTHON=python3
      export V=1

      sed --in-place \
        --expression 's:^SYS_PREFIX=.*:SYS_PREFIX=${SNAP_COMMON}:' \
        deps/rabbit/scripts/rabbitmq-defaults

      make -j ${CPU_COUNT} dist manpages
      
      make install
      make install-bin

      echo "Finished building rabbitmq-server at $(date)"
      END_TIME=$(date +%s)
      echo "Total time: $((${END_TIME} - ${START_TIME})) seconds"

  elixir:
    after:
      - erlang
    plugin: dump
    source: https://github.com/elixir-lang/elixir.git
    source-tag: v1.13.4
    source-depth: 1
    override-build: |
      set -e -u -x

      echo "Starting to build elixir at $(date)"
      START_TIME=$(date +%s)

      CPU_COUNT=$(lscpu --parse=CPU | grep -v "^#" | wc -l)

      export DESTDIR="$(readlink --canonicalize ${SNAPCRAFT_PART_INSTALL})"
      export PREFIX=/usr

      make clean
      make -j ${CPU_COUNT}
      # make -j ${CPU_COUNT} test
      make install

      echo "Finished building elixir at $(date)"
      END_TIME=$(date +%s)
      echo "Total time: $((${END_TIME} - ${START_TIME})) seconds"
    stage:
      - usr

  erlang:
    plugin: dump
    source: https://github.com/erlang/otp.git
    source-tag: OTP-24.3.4.2
    source-depth: 1
    build-packages:
      - autoconf
      - fop
      - libssl-dev
      - libncurses5-dev
      - libwxbase3.0-dev
      - libxml2-utils
      - xsltproc
    stage-packages:
      - openssl
      - ncurses-base
      - libncurses5
      - libtinfo5
    override-build: |
      set -e -u -x

      echo "Starting to build erlang at $(date)"
      START_TIME=$(date +%s)

      CPU_COUNT=$(lscpu --parse=CPU | grep -v "^#" | wc -l)

      export DESTDIR="$(readlink --canonicalize ${SNAPCRAFT_PART_INSTALL})"

      ./otp_build update_configure
      ./configure --prefix=/usr

      make -j ${CPU_COUNT}
      make install

      sed --in-place \
        --expression 's:^\(\s*ROOTDIR\)="/usr/.*":\1=$(readlink --canonicalize $(dirname $0)/../lib/erlang):' \
        ${SNAPCRAFT_PART_INSTALL}/usr/bin/erl
      sed --in-place \
        --expression 's:^\(\s*ROOTDIR\)="/usr/.*":\1=$(readlink --canonicalize $(dirname $0)/../..):' \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/erlang/erts-*/bin/start
      sed --in-place \
        --expression 's:^\(\s*ROOTDIR\)="/usr/.*":\1=$(readlink --canonicalize $(dirname $0)/../..):' \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/erlang/erts-*/bin/erl
      sed --in-place \
        --expression 's:^\(\s*ROOTDIR\)="/usr/.*":\1=$(readlink --canonicalize $(dirname $0)/..):' \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/erlang/bin/start
      sed --in-place \
        --expression 's:^\(\s*ROOTDIR\)="/usr/.*":\1=$(readlink --canonicalize $(dirname $0)/..):' \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/erlang/bin/erl

      echo "Finished building erlang at $(date)"
      END_TIME=$(date +%s)
      echo "Total time: $((${END_TIME} - ${START_TIME})) seconds"
    stage:
      - etc
      - lib
      - usr
