---

name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft
      - name: Install rabbitmq-server snap
        run: |
          sudo snap install --devmode ./rabbitmq-server-snap*.snap
      - name: Wait for rabbitmq-server to start
        run: |
          set -e -u -x
          success=0
          for i in $(seq 10); do
            if sudo snap services rabbitmq-server-snap | grep --quiet enabled; then
              success=1
              break
            fi
            sleep 2
          done
          (( ${success} == 1 ))
          success=0
          for i in $(seq 10); do
            if sudo snap services rabbitmq-server-snap | grep --quiet active; then
              success=1
              break
            fi
            sleep 2
          done
          (( ${success} == 1 ))
      - name: Check server logs
        run: |
          set -e -u -x
          success=0
          for i in $(seq 10); do
            if sudo snap logs rabbitmq-server-snap.rabbitmq-server | grep --quiet "Starting broker"; then
              success=1
              break
            fi
            sleep 2
          done
          (( ${success} == 1 ))
      - name: Check whether process is running
        run: pgrep -alf bin/rabbitmq-server
      - name: Check cluster status
        run: |
          set -e -u -x
          success=0
          for i in $(seq 10); do
            if sudo rabbitmq-server-snap.rabbitmqctl cluster_status; then
              success=1
              break
            fi
            sleep 2
          done
          (( ${success} == 1 ))
      - name: Check queues
        run: |
          set -e -u -x

          sudo pip install RabbitMQ-Test-Tool
      - name: Store snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
